const works = [
  {
    image:
      'https://drscdn.500px.org/photo/286129421/q%3D80_m%3D2000_k%3D1/v2?sig=db63a820f92f9491737fc0492d8ff2fe334513565c2099430f0da9b1a1b5bf34',
    type: 'Project',
    title: 'Krypt',
    desc: 'A Web3 - Blockchain based project that lets you transfer ETHereums from your wallet to a reciever.',
    auth_name: 'Tanay Srivastava',
    auth_img: 'https://avatars.githubusercontent.com/u/62954323?v=4',
    link: '',
    linkGH: 'https://github.com/Ta5r/First-Blockchain-App',
    tags: 'Solidity,React,HardHat',
    status: 'ongoing',
    date: 'Feb 08, 2021',
  },
  {
    image:
      'https://res.cloudinary.com/dfoxozwkm/image/upload/v1660027097/me-ta5r/genesis_ohknz3.png',
    type: 'Project',
    title: 'GENESIS',
    desc: 'A website for the annual Tech Fest of IEEE MUJ. Genesis is the largest tech fest of Manipal University Jaipur.',
    auth_name: 'Tanay Srivastava',
    auth_img: 'https://avatars.githubusercontent.com/u/62954323?v=4',
    link: 'https://genisys.vercel.app/',
    linkGH: 'https://github.com/Ta5r/Genisys',
    tags: 'NextJS,React,ChakraUI',
    status: 'ongoing',
    date: 'Aug 04, 2022',
  },
  {
    image:
      'https://res.cloudinary.com/dfoxozwkm/image/upload/v1660027042/me-ta5r/iow_kxmyxr.png',
    type: 'Project',
    title: 'IOW Complaint Management System',
    desc: 'This is a Complaint Managment System build for RDSO colony, Lucknow. It is a React App with a backend based on Express and NodeJS. The Database used is MongoDB.',
    auth_name: 'Tanay Srivastava',
    auth_img: 'https://avatars.githubusercontent.com/u/62954323?v=4',
    link: '#',
    linkGH: 'https://github.com/Ta5r/ServiceRequest',
    tags: '',
    status: 'completed',
    date: 'Jun 24, 2022',
  },
  {
    image:
      'https://ieeemuj.com/nextimg/%2F_next%2Fstatic%2Fimage%2Fpublic%2Fimgs%2Flogo.e5f47e2260ea17e37c2a76b835da1384.png/3840/75?url=%2F_next%2Fstatic%2Fimage%2Fpublic%2Fimgs%2Flogo.e5f47e2260ea17e37c2a76b835da1384.png&w=3840&q=75',
    type: 'Project',
    title: 'IEEEMUJ.com',
    desc: 'This is the official website for IEEE SB MUJ which provides information to all the active and past events organized by IEEE MUJ, IEEE Teams and many more.',
    auth_name: 'Tanay Srivastava',
    auth_img: 'https://avatars.githubusercontent.com/u/62954323?v=4',
    link: 'https://www.ieeemuj.com',
    linkGH: '#',
    tags: 'ReactJS,ChakraUI,Prismic CMS',
    status: 'completed',
    date: 'Jun 15, 2021',
  },
  {
    image:
      'https://drscdn.500px.org/photo/261273205/q%3D80_m%3D2000/v2?sig=f805af233a6dbd5c25285b12b1c65c3aaa178bffb8c6b0ea5232179b70f81172',
    type: 'Project',
    title: 'Piklash',
    desc: 'Piklash is a Selfie contest website where users upvote or downvote other profiles which in turn updates the Leaderboard',
    auth_name: 'Tanay Srivastava',
    auth_img: 'https://avatars.githubusercontent.com/u/62954323?v=4',
    link: '#',
    linkGH: 'https://github.com/Ta5r/Piklash',
    tags: 'ReactJS,ExpressJS,Cloudinary,MongoDB,Tinder-Cards',
    status: 'completed',
    date: 'Feb 08, 2022',
  },
  {
    image:
      'https://res.cloudinary.com/dfoxozwkm/image/upload/v1660027040/me-ta5r/sorting_omamdd.png',
    type: 'Project',
    title: 'Algorith Visualizer',
    desc: 'A simple web based algorith visualizer made using JavaScript',
    auth_name: 'Tanay Srivastava',
    auth_img: 'https://avatars.githubusercontent.com/u/62954323?v=4',
    link: 'https://ta5r.github.io/Algorithm-Visualizer/',
    linkGH: 'https://github.com/Ta5r/Algorithm-Visualizer',
    tags: 'HTML,JavaScript,CSS',
    status: 'completed',
    date: 'Jan 08, 2021',
  },
  {
    image:
      'https://res.cloudinary.com/dfoxozwkm/image/upload/v1660027041/me-ta5r/pokedex_img_ixwpbt.png',
    type: 'Project',
    title: 'Pokedex',
    desc: 'A webapp created to catalog information regarding the various species of Pokémon featured in the Pokémon video game, anime and manga series.',
    auth_name: 'Tanay Srivastava',
    auth_img: 'https://avatars.githubusercontent.com/u/62954323?v=4',
    link: 'https://pokedex-ta5r.vercel.app/',
    linkGH: 'https://github.com/Ta5r/pokedex',
    tags: 'React,API,CSS',
    status: 'completed',
    date: 'Jan 16, 2022',
  },
  {
    image:
      'https://images.unsplash.com/photo-1456428746267-a1756408f782?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1470&q=80',
    type: 'Project',
    title: 'Troy',
    desc: 'A webapp created to add and manage contacts and their data like images and more.It reminds you of important events related to these contacts and many more exciting features.',
    auth_name: 'Tanay Srivastava',
    auth_img: 'https://avatars.githubusercontent.com/u/62954323?v=4',
    link: '',
    linkGH: 'https://github.com/Ta5r/TroyETE',
    tags: 'PHP,MySQL,Bootstrap',
    status: 'completed',
    date: 'May 24, 2021',
  },
];

export default works;
